dist: trusty
sudo: false

# Prerequisites
before_install:
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
  
# Build steps
script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .
  - cmake --build .
  #- cmake --build . --target install

install:
  