set(INSTALL_SUBMODULES_RUN ${CMAKE_INSTALL_PREFIX}/bin CACHE INTERNAL "")
set(INSTALL_SUBMODULES_ARC ${CMAKE_INSTALL_PREFIX}/lib CACHE INTERNAL "") 
set(INSTALL_SUBMODULES_LIB ${CMAKE_INSTALL_PREFIX}/lib CACHE INTERNAL "")
set(INSTALL_SUBMODULES_INC ${CMAKE_INSTALL_PREFIX}/include CACHE INTERNAL "")