set(INSTALL_SUBMODULES_RUN ${INSTALL_SUBMODULES_DIR}/bin CACHE INTERNAL "installation")
set(INSTALL_SUBMODULES_ARC ${INSTALL_SUBMODULES_DIR}/lib CACHE INTERNAL "installation") 
set(INSTALL_SUBMODULES_LIB ${INSTALL_SUBMODULES_DIR}/lib CACHE INTERNAL "installation")
set(INSTALL_SUBMODULES_INC ${INSTALL_SUBMODULES_DIR}/include CACHE INTERNAL "installation")